var masterDataArr = [
    { name: 'vehicleBooking', modelPath: '../../databases/salesMaster/models/01.vehicleBooking' },
    { name: 'insuranceSettlementType', modelPath: '../../databases/salesMaster/models/02.insuranceSettlementType' },
    { name: 'bookingType', modelPath: '../../databases/salesMaster/models/03.bookingType' },
    { name: 'leadSource', modelPath: '../../databases/salesMaster/models/04.leadSource' },
    { name: 'leadSourceGroup', modelPath: '../../databases/salesMaster/models/05.leadSourceGroup' },
    { name: 'leadType', modelPath: '../../databases/salesMaster/models/06.leadType' },
    { name: 'lead', modelPath: '../../databases/salesMaster/models/07.lead' },
    { name: 'leadCustomer', modelPath: '../../databases/salesMaster/models/08.leadCustomer' },
    { name: 'leadVehicleOwn', modelPath: '../../databases/salesMaster/models/09.leadVehicleOwn' },
    { name: 'exciseType', modelPath: '../../databases/salesMaster/models/10.exciseType' },
    { name: 'vehicleBookingRefund', modelPath: '../../databases/salesMaster/models/11.vehicleBookingRefund' },
    { name: 'accessoriesDismantle', modelPath: '../../databases/salesMaster/models/12.accessoriesDismantle' },
    // { name: 'warrantyProfile', modelPath: '../../databases/salesMaster/models/11.warrantyProfile' },
    // { name: 'warrantyCategory', modelPath: '../../databases/salesMaster/models/12.warrantyCategory' },
    // { name: 'forecast', modelPath: '../../databases/salesMaster/models/13.forecast' },
    // { name: 'forecastApproval', modelPath: '../../databases/salesMaster/models/14.forecastApproval' },
    // { name: 'forecastSetup', modelPath: '../../databases/salesMaster/models/15.forecastSetup' },
    // { name: 'forecastSetupData', modelPath: '../../databases/salesMaster/models/16.forecastSetupData' },
    // { name: 'target', modelPath: '../../databases/salesMaster/models/17.target' },
    // { name: 'targetSetup', modelPath: '../../databases/salesMaster/models/18.targetSetup' },
    // { name: 'targetSetupData', modelPath: '../../databases/salesMaster/models/19.targetSetupData' },
    // { name: 'order', modelPath: '../../databases/salesMaster/models/20.order' },
    // { name: 'orderSetup', modelPath: '../../databases/salesMaster/models/21.orderSetup' },
    // { name: 'orderSetupModel', modelPath: '../../databases/salesMaster/models/22.orderSetupModel' },
    // { name: 'orderSetupVariant', modelPath: '../../databases/salesMaster/models/23.orderSetupVariant' },
    // { name: 'orderSetupProduct', modelPath: '../../databases/salesMaster/models/24.orderSetupProduct' },
    // { name: 'orderSetupColor', modelPath: '../../databases/salesMaster/models/25.orderSetupColor' },
    // { name: 'orderList', modelPath: '../../databases/salesMaster/models/26.orderList' },
    { name: 'orderListSetup', modelPath: '../../databases/salesMaster/models/27.orderListSetup' },
    // { name: 'adhocOrder', modelPath: '../../databases/salesMaster/models/28.adhocOrder' },
    // { name: 'adhocOrderSetup', modelPath: '../../databases/salesMaster/models/29.adhocOrderSetup' },
    // { name: 'adhocOrderSetupModel', modelPath: '../../databases/salesMaster/models/30.adhocOrderSetupModel' },
    // { name: 'adhocOrderSetupVariant', modelPath: '../../databases/salesMaster/models/31.adhocOrderSetupVariant' },
    // { name: 'adhocOrderSetupProduct', modelPath: '../../databases/salesMaster/models/32.adhocOrderSetupProduct' },
    // { name: 'adhocOrderSetupColor', modelPath: '../../databases/salesMaster/models/33.adhocOrderSetupColor' },
    { name: 'vehicleBookingTradeInDetail', modelPath: '../../databases/salesMaster/models/34.vehicleBookingTradeInDetail' },
    // { name: 'adhocOrderPreorder', modelPath: '../../databases/salesMaster/models/35.adhocOrderPreorder' },
    { name: 'accessoriesFitment', modelPath: '../../databases/salesMaster/models/36.accessoriesFitment' },
    { name: 'accessoriesItem', modelPath: '../../databases/salesMaster/models/37.accessoriesItem' },
    { name: 'accessoriesFitmentDocument', modelPath: '../../databases/salesMaster/models/38.accessoriesFitmentDocument' },
    { name: 'usedVehicleBooking', modelPath: '../../databases/salesMaster/models/48.usedVehicleBookingData' },
]

module.exports = masterDataArr
