var masterDataArr = [
    { name: 'make', modelPath: '../../databases/specMaster/models/01.make' },
    { name: 'model', modelPath: '../../databases/specMaster/models/02.model' },
    { name: 'variant', modelPath: '../../databases/specMaster/models/03.variant' },
    { name: 'transmissionType', modelPath: '../../databases/specMaster/models/04.transmissionType' },
    { name: 'bodyType', modelPath: '../../databases/specMaster/models/05.bodyType' },
    { name: 'vehicleType', modelPath: '../../databases/specMaster/models/06.vehicleType' },
    { name: 'engineType', modelPath: '../../databases/specMaster/models/07.engineType' },
    { name: 'assemblyType', modelPath: '../../databases/specMaster/models/08.assemblyType' },
    { name: 'vehicle', modelPath: '../../databases/specMaster/models/09.vehicle' },
    { name: 'colorType', modelPath: '../../databases/specMaster/models/10.colorType' },
    { name: 'color', modelPath: '../../databases/specMaster/models/11.color' },
    { name: 'vehicleUsage', modelPath: '../../databases/specMaster/models/12.vehicleUsage' },
    { name: 'product', modelPath: '../../databases/specMaster/models/13.product' },
    { name: 'customerVehicleRelation', modelPath: '../../databases/specMaster/models/14.customerVehicleRelation' },
    { name: 'packageUsage', modelPath: '../../databases/specMaster/models/15.packageUsage' },
    { name: 'packageType', modelPath: '../../databases/specMaster/models/16.packageType' },
    { name: 'package', modelPath: '../../databases/specMaster/models/17.package' },
    { name: 'vehicleBusinessType', modelPath: '../../databases/specMaster/models/19.vehicleBusinessType' },
    { name: 'vehicleAccessories', modelPath: '../../databases/specMaster/models/20.vehicleAccessories' },
    { name: 'vehicleMovement', modelPath: '../../databases/specMaster/models/23.vehicleMovement' },
    { name: 'vehicleSalesServiceHistory', modelPath: '../../databases/specMaster/models/25.vehicleSalesServiceHistory' },
    { name: 'vehicleRegistration', modelPath: '../../databases/specMaster/models/26.vehicleRegistration' },
    { name: 'customerVehicleRelationHistory', modelPath: '../../databases/specMaster/models/27.customerVehicleRelationHistory' },
    { name: 'vehicleKey', modelPath: '../../databases/specMaster/models/28.vehicleKey' },
    { name: 'keys', modelPath: '../../databases/specMaster/models/29.keys' },
    { name: 'registrationType', modelPath: '../../databases/specMaster/models/30.registrationType' },
    { name: 'vehicleStock', modelPath: '../../databases/customerMaster/models/7.company' },
    { name: 'vehicleLocation', modelPath: '../../databases/customerMaster/models/18.branch' },
    { name: 'vehicleStorage', modelPath: '../../databases/customerMaster/models/20.storageLocation' },
    { name: 'customer', modelPath: '../../databases/customerMaster/models/10.customer' },
]

module.exports = masterDataArr
