var masterDataArr = [
    { name: 'country', modelPath: '../../databases/generalMaster/models/01.country' },
    { name: 'state', modelPath: '../../databases/generalMaster/models/02.state' },
    { name: 'city', modelPath: '../../databases/generalMaster/models/03.city' },
    { name: 'postcode', modelPath: '../../databases/generalMaster/models/04.postcode' },
    { name: 'timezone', modelPath: '../../databases/generalMaster/models/05.timezone' },
    { name: 'language', modelPath: '../../databases/generalMaster/models/06.language' },
    { name: 'region', modelPath: '../../databases/generalMaster/models/07.region' },
    { name: 'education', modelPath: '../../databases/generalMaster/models/08.education' },
    { name: 'religion', modelPath: '../../databases/generalMaster/models/09.religion' },
    { name: 'salutation', modelPath: '../../databases/generalMaster/models/10.salutation' },
    { name: 'ethnicity', modelPath: '../../databases/generalMaster/models/11.ethnicity' },
    { name: 'identity', modelPath: '../../databases/generalMaster/models/12.identity' },
    { name: 'preferModeOfContact', modelPath: '../../databases/generalMaster/models/13.preferModeOfContact' },
    { name: 'currency', modelPath: '../../databases/generalMaster/models/14.currency' },
    { name: 'topicSeries', modelPath: '../../databases/generalMaster/models/15.topic-series' },
    { name: 'uom', modelPath: '../../databases/generalMaster/models/16.uom' },
    { name: 'itemCategory', modelPath: '../../databases/generalMaster/models/17.itemCategory' },
    { name: 'materialType', modelPath: '../../databases/generalMaster/models/18.materialType' },
    { name: 'materialMaster', modelPath: '../../databases/generalMaster/models/19.materialMaster' },    // diff name
    { name: 'materialContractor', modelPath: '../../databases/generalMaster/models/20.materialContractor' },
    { name: 'campaign', modelPath: '../../databases/generalMaster/models/21.campaign' },
    { name: 'material', modelPath: '../../databases/generalMaster/models/22.materialGroupCode' },       // diff name
    { name: 'quantityConversion', modelPath: '../../databases/generalMaster/models/26.materialQuantityConv' },
    { name: 'materialProcurement', modelPath: '../../databases/generalMaster/models/27.materialProcurement' },
    { name: 'materialSales', modelPath: '../../databases/generalMaster/models/28.materialSales' },
    { name: 'materialAccounting', modelPath: '../../databases/generalMaster/models/29.materialAccounting' },
    { name: 'materialStorage', modelPath: '../../databases/generalMaster/models/30.materialStorage' },
    { name: 'materialSuperSession', modelPath: '../../databases/generalMaster/models/31.materialSuperSession' },
    { name: 'vendorBasic', modelPath: '../../databases/generalMaster/models/32.vendorBasic' },
    { name: 'vendorCommunication', modelPath: '../../databases/generalMaster/models/33.vendorCommunication' },
    { name: 'vendorGroup', modelPath: '../../databases/generalMaster/models/34.vendorGroup' },
    { name: 'vendorAccountGroup', modelPath: '../../databases/generalMaster/models/35.vendorAccountGroup' },
    { name: 'paymentMethod', modelPath: '../../databases/generalMaster/models/36.paymentMethod' },
    { name: 'vendorBusinessFinancial', modelPath: '../../databases/generalMaster/models/37.vendorBusinessFinancial' },
    { name: 'vendorBusinessPurchasing', modelPath: '../../databases/generalMaster/models/38.vendorBusinessPurchasing' },
    { name: 'vendorBusinessBankData', modelPath: '../../databases/generalMaster/models/39.vendorBusinessBankData' },
    { name: 'campaignType', modelPath: '../../databases/generalMaster/models/40.campaignType' },
    { name: 'campaignIssuance', modelPath: '../../databases/generalMaster/models/41.campaignIssuance' },
    { name: 'campaignRedemption', modelPath: '../../databases/generalMaster/models/42.campaignRedemption' },
    { name: 'termsAndCondition', modelPath: '../../databases/generalMaster/models/43.termsAndCondition' },
    { name: 'termsAndConditionTemplate', modelPath: '../../databases/generalMaster/models/44.termsAndConditionTemplate' },
    { name: 'eVoucher', modelPath: '../../databases/generalMaster/models/45.evoucher' },
    { name: 'vehicleList', modelPath: '../../databases/generalMaster/models/46.vehicleList' },
    { name: 'payment', modelPath: '../../databases/generalMaster/models/47.payment' },
    { name: 'paymentDeposit', modelPath: '../../databases/generalMaster/models/48.paymentDeposit' },
    { name: 'warrantyCategory', modelPath: '../../databases/generalMaster/models/52.warrantyCategory' },
    { name: 'warrantyProfile', modelPath: '../../databases/generalMaster/models/53.warrantyProfile' },
    { name: 'rejectedReason', modelPath: '../../databases/generalMaster/models/61.rejectedReason' },
    { name: 'registrationRegion', modelPath: '../../databases/generalMaster/models/62.registrationRegion' },
    { name: 'constantParameter', modelPath: '../../databases/generalMaster/models/89.constantParameter' },
    { name: 'materialMasterBasicinfo', modelPath: '../../databases/generalMaster/models/19.materialMaster' },
    { name: 'areaOperatorCode', modelPath: '../../databases/generalMaster/models/60.areaOperatorCode' },
]

module.exports = masterDataArr
